### ISSUE TITLE
How to set the scope for the whole folder?

### ISSUE THREAD

**Issue by fregante** [A-Shleifman/eslint-plugin-export-scope#1]
> Set default export scope (visibility) for the whole project/folder/file or for individual exports.

It seems that the plugin can automatically pick up the configuration based on the folder name. Is there a way to set the scope for a whole folder without having to change its name? It would be good to include this information in the readme.

It seems that currently I'd have to create an override for the specific folders and set `strict: true` for them, for example:

```json
"overrides": [{
  "files": ["restricted/*", "dont-import-me/*"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "project": "tsconfig.json" },
  "plugins": ["export-scope"],
  "rules": {
    "export-scope/no-imports-outside-export-scope": [
      "error",
      { "strictMode": true }
    ]
  }
}]
```

Is this correct? 

[I'm currently using](https://github.com/pixiebrix/pixiebrix-extension/blob/f427bbc9bf16274e7863b7330a7c9024d0ee959a/.eslintrc.js#L1-L34) `import/no-restricted-path` for this and I wonder if this would be more performant or offer a better experience in the IDE.

**Comment by A-Shleifman** [comment]
I was considering different ways of handling folder-level scope declarations. At the moment only prepending folder names with `@ - global`, `@. - current folder`, `@..`, e.t.c. is supported. Prepending folder names also makes accessibility of that folder explicit. `@utils` is clearly importable anywhere.

Defining a map of folder scopes like in `import/no-restricted-path` will make refactoring harder as it will have to be manually maintained. 

I wouldn't rule this approach out, but I would like to see a bit more demand for this feature before implementing it.

Ideally, projects would have `strictMode` enabled by default and only override it when necessary. It might not be an option for existing large projects though.

I don't know how performant `no-restricted-path` is. This plugin shouldn't have any performance issues. It is an ESLint/TS plugin, so in addition to displaying ESLint errors, it is also preventing the IDE from displaying imports outside their scope.

Looks like you're already using `@` to map imports to `src` in your project. This probably won't conflict with this plugin, but `@/@utils` might not be the prettiest import in the world.

Another option would be to add support for files like `.scope[..]` that would be placed in folders to modify their scope. That would solve the refactoring problem, but I'm not sure how I feel about it yet.

**Comment by ciriousjoker** [comment]
A barrel file seems like a good approach to me:

```ts
/** @scope default * */
export * from "./somefile";
...
```

At least in our case, we have those for our utility folders already.

**Comment by ciriousjoker** [comment]
@A-Shleifman Is my approach from above supposed to work? I just tested it and it doesn't actually work :(

**Comment by A-Shleifman** [comment]
@ciriousjoker, I didn't have a test case for star exports (added now), but your example should be working fine.

```ts
/** @scope default * */
export * from "./somefile";
```

I don't know what your setup is. If `@org` is the name of the folder, then no additional `@scope` declarations are required. `@` prefix in folder/file names makes all descendant exports global. If `@org` is an alias, then, yes, a declaration is required.

**Comment by ciriousjoker** [comment]
Yes, org is the tsconfig oath name. It's no big deal though since it's just one scope statement for the whole folder

**Comment by RobMayer** [comment]
I just ran into a situation where a blanket folder decleration would be useful. I don't mind the barrel approach, but it seems feels odd to have a dedicated script just to re-export. It's a viable pattern, but one that doesn't jive with me.
a ".scope" folder in the directory feels right to me, for what it's worth.

**Comment by A-Shleifman** [comment]
What do you think about [v2](https://github.com/A-Shleifman/eslint-plugin-export-scope/tree/v2)? The new approach will allow setting folder scopes without affecting folder names.

**Comment by ciriousjoker** [comment]
@A-Shleifman im really not a fan of the ^ sign. As an optional shorthand it's good, but I much prefer the scope + path annotation since even new devs on the project and external people intuitively understand it. Why not keep the scope tsdoc and add for files for folders? `.scope` and the content of the file is the path.

**Comment by ciriousjoker** [comment]
Makes sense. Given how rare those files tend to be based on my experience I would personally still lean towards the scope filename.

Maybe allow both filenames types? I haven't worked with either yet though so I don't know how well either works in practice though.

**Comment by A-Shleifman** [comment]
I have quite a lot of those files in my project, but having scope files would allow tapping into the autocomplete engine. Playing around with `.scope.ts` files + `@scope` JSDoc property at the moment.

![2024-01-09 22 27 24](https://github.com/A-Shleifman/eslint-plugin-export-scope/assets/1146193/b56296b7-b414-488e-aa5b-17815c672d01)

**Comment by A-Shleifman** [comment]
[A version with `.scope.ts` files](https://github.com/A-Shleifman/eslint-plugin-export-scope/tree/v2) 

`@` snippet satisfies my laziness 😄
