### ISSUE TITLE
Exceptions to strict mode?

### ISSUE THREAD

**Issue by ciriousjoker** [A-Shleifman/eslint-plugin-export-scope#2]
We'd like to add exceptions while also using strict mode.

There's one special file in our repo which we use as a mini-testcase. In this file we'd like to import anything from anywhere in order to allow quick prototyping without fiddling with import settings first.

Is something like this planned?

**Comment by A-Shleifman** [comment]
In Strict Mode files like that are probably exceptions, so how about just disabling the ESLint rule for the file and adding imports manually (without autocomplete)?

```ts
/* eslint-disable export-scope/no-imports-outside-export-scope */

import something from 'another/scope';
```

Or do you think another annotation that would re-enable autocomplete would make it much easier?

**Comment by ciriousjoker** [comment]
oooh good point, I completely forgot that you can disable them. This perfectly solves it for that single file we would be using that feature on.
